#!/usr/bin/env php
<?php
// bin/dbup

$candidateAutoloaders = [
    __DIR__ . '/vendor/autoload.php',  // This file is placed on the Dbup root
    __DIR__ . '/../../autoload.php',  // This file is placed on the vendor/brtriver/dbup by Composer (symlinked)
    __DIR__ . '/../autoload.php',  // This file is placed on the vendor/bin by Composer (hard-copied)
];

$autoloaderPath = '';
foreach ($candidateAutoloaders as $candidate) {
    if (is_file($candidate)) {
        $autoloaderPath = $candidate;
        break;
    }
}

if (!$autoloaderPath) {
    trigger_error('Any autoloaders cannot be detected', E_USER_ERROR);
}

require_once $autoloaderPath;

$application = new \Dbup\Application();
$application->add(new \Dbup\Command\InitCommand);
$application->add(new \Dbup\Command\StatusCommand);
$application->add(new \Dbup\Command\UpCommand);
$application->add(new \Dbup\Command\CompileCommand);
$application->add(new \Dbup\Command\CreateCommand);
$application->run();
